# Generated by Django 4.0.4 on 2022-06-12 02:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0002_added_form_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('is_first_name_visible', models.BooleanField(default=True)),
                ('is_middle_name_visible', models.BooleanField(default=True)),
                ('is_last_name_visible', models.BooleanField(default=True)),
                ('first_name_sublabel', models.CharField(default='First Name', max_length=200)),
                ('middle_name_sublabel', models.CharField(default='Middle Name', max_length=200)),
                ('last_name_sublabel', models.CharField(default='Last Name', max_length=200)),
                ('first_name_placeholder', models.CharField(default='', max_length=200)),
                ('middle_name_placeholder', models.CharField(default='', max_length=200)),
                ('last_name_placeholder', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_field_font_size', models.IntegerField(blank=True, null=True)),
                ('label_font_size', models.IntegerField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_name_elements', to='tzapp.form')),
            ],
            options={
                'db_table': 'name_elements',
            },
        ),
    ]
