# Generated by Django 4.0.4 on 2022-06-12 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0003_added_name_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('is_street_visible', models.BooleanField(default=True)),
                ('is_state_visible', models.BooleanField(default=True)),
                ('is_country_visible', models.BooleanField(default=True)),
                ('is_city_visible', models.BooleanField(default=True)),
                ('state_sublabel', models.CharField(default='State', max_length=200)),
                ('country_sublabel', models.CharField(default='Country', max_length=200)),
                ('street_sublabel', models.CharField(default='Street Address', max_length=200)),
                ('city_sublabel', models.CharField(default='City', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_field_font_size', models.IntegerField(blank=True, null=True)),
                ('label_font_size', models.IntegerField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_address_elements', to='tzapp.form')),
            ],
            options={
                'db_table': 'address_elements',
            },
        ),
    ]
