# Generated by Django 4.0.5 on 2022-06-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0003_added_element_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='order',
            new_name='elements',
        ),
    ]
