# Generated by Django 4.0.5 on 2022-06-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0004_rename_form_order_to_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='layouts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
