# Generated by Django 4.0.5 on 2022-06-26 01:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0006_added_submission_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
    ]
