# Generated by Django 4.0.5 on 2022-06-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0007_change_default_base_field_of_form_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='validations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('page_break', 'page_break'), ('input_field', 'input_field'), ('checkbox_field', 'checkbox_field'), ('radio_field', 'radio_field'), ('file_upload', 'file_upload')], max_length=20),
        ),
    ]
