# Generated by Django 4.0.5 on 2022-08-14 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0008_element_validations_alter_element_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('view_count', models.IntegerField(default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_views', to='cleanform.form')),
            ],
            options={
                'db_table': 'form_views',
                'unique_together': {('form', 'ip_address')},
            },
        ),
    ]
