# Generated by Django 4.0.5 on 2022-08-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0009_added_form_view_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SMTP', 'SMTP'), ('SDK', 'SDK')], default='SMTP', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=10)),
                ('tls_enabled', models.BooleanField(default=True)),
                ('_host_user', models.CharField(db_column='host_user', max_length=100)),
                ('_host_password', models.CharField(db_column='host_password', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_services',
            },
        ),
    ]
