# Generated by Django 4.0.5 on 2022-08-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0010_added_email_service_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_responder_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='responder_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='responder_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='responder_email_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_service_forms', to='cleanform.emailservice'),
        ),
        migrations.AddField(
            model_name='form',
            name='responder_target_email_label',
            field=models.CharField(default='email', max_length=100),
        ),
    ]
