# Generated by Django 4.0.5 on 2022-08-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0011_added_autoresponder_configuration_to_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='responder_description',
        ),
        migrations.RemoveField(
            model_name='form',
            name='responder_email',
        ),
        migrations.RemoveField(
            model_name='form',
            name='responder_email_service',
        ),
        migrations.RemoveField(
            model_name='form',
            name='responder_target_email_label',
        ),
    ]
