# Generated by Django 4.0.5 on 2022-08-15 04:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0012_removed_responder_settings_from_form_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('target_email_label', models.CharField(default='email', max_length=100)),
                ('email_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_service_responders', to='cleanform.emailservice')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responders', to='cleanform.form')),
            ],
            options={
                'db_table': 'responders',
            },
        ),
    ]
