# Generated by Django 4.0.5 on 2022-08-15 04:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanform', '0013_added_responder_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_logs', to='cleanform.responder')),
            ],
            options={
                'db_table': 'responder_logs',
            },
        ),
    ]
